/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OdDS93vquhe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"
import { Button } from "@/components/ui/button"

export function FrequentQuestions() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 grid gap-4 md:gap-6">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">FAQ</h2>
          <p className="text-gray-500 md:text-xl/relaxed dark:text-gray-400">
            Got a question? We've got answers. If you have other questions, please email support.
          </p>
        </div>
        <div className="space-y-4">
          <Collapsible className="grid">
            <CollapsibleTrigger asChild>
              <Button className="w-full justify-start text-left font-semibold">
                Can I upgrade my plan later?
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent asChild>
              <p className="text-sm leading-loose text-gray-500 md:text-base dark:text-gray-400">
                Yes. You can start or stop your plan at any time.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid">
            <CollapsibleTrigger asChild>
              <Button className="w-full justify-start text-left font-semibold">
                Can I switch plans?
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent asChild>
              <p className="text-sm leading-loose text-gray-500 md:text-base dark:text-gray-400">
                Yes. You can start or stop your plan at any time.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid">
            <CollapsibleTrigger asChild>
              <Button className="w-full justify-start text-left font-semibold">
                Do you offer a discount for non-profit
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent asChild>
              <p className="text-sm leading-loose text-gray-500 md:text-base dark:text-gray-400">
                Yes. You can start or stop your plan at any time.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid">
            <CollapsibleTrigger asChild>
              <Button className="w-full justify-start text-left font-semibold">
                How secure is your service?
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent asChild>
              <p className="text-sm leading-loose text-gray-500 md:text-base dark:text-gray-400">
                Yes. You can start or stop your plan at any time.
              </p>
            </CollapsibleContent>
          </Collapsible>
          <Collapsible className="grid">
            <CollapsibleTrigger asChild>
              <Button className="w-full justify-start text-left font-semibold">
                Can I cancel at any time?
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent asChild>
              <p className="text-sm leading-loose text-gray-500 md:text-base dark:text-gray-400">
                Yes. You can start or stop your plan at any time.
              </p>
            </CollapsibleContent>
          </Collapsible>
        </div>
      </div>
    </section>
  )
}
